### ISSUE TITLE
How to close other tooltips?

### ISSUE THREAD

**Issue by circlecodesolution** [yjose/reactjs-popup#116] opened 2019-08-14 01:09 UTC
https://codesandbox.io/embed/reactjs-popup-issue-template-q9hpl
![image](https://user-images.githubusercontent.com/53724147/62987586-28aadb80-be5e-11e9-881e-d4b567dbeab0.png)

### Test Case
https://codesandbox.io/s/n5q4zqw2n0

**Comment by alekslario** [comment] 2019-09-23 02:18
Same as #101

**Comment by zakariaelas** [comment] 2019-11-29 15:39
@yjose I have looked through this. I don't think the solution proposed in #101 solves the problem, onClickCapture would not work in this case. I believe that the problem is related to the stacking order in this specific example.
The following sequence of actions will help prove this point further: 

1. When clicking the first button, notice how clicking any of the other buttons successfully dismisses the first popup. This is because the overlay that is appended to the DOM (as sibling to the first trigger button) is absolutely positioned. This gives it a higher stacking order than its siblings, in this case, all the adjacent trigger buttons. So, so far, no problem, and clicking any button successfully dismisses the popup just as expected.
2. Now that the popup is dismissed, click the second button. This sets the second trigger button's position to relative. The tricky part is that even after the popup is dismissed the trigger button keeps its relative position. This makes the second trigger button have a higher stacking order than in 1.
3. Now try clicking the first trigger button again. Following is a "snapshot" of the DOM at this point in time: 
```
<button style="position: relative;">Trigger</button>
<div style="position: absolute; top: 0px; left: 0px;"></div>
<div class="popup-overlay " style="position: fixed; top: 0px; bottom: 0px; left: 0px; right: 0px;"></div>
<button style="position: relative;">Trigger</button>
...popup
...other buttons
```
Try clicking the second button right after. Now you will notice that both popups overlap and that the first popup is not dismissed (not the behavior we would expect).
Explanation: This happens because the second button has a higher stacking order. Now that both the div.popup-overlay and second button are positioned, the **button** will have **higher** stacking order because it **appears** **after** the div.popup-overlay. Thus the button intercepts the event instead of our overlay div. 

### Suggested fix:
We can make the overlay have higher stacking order by giving it the following style property `z-index: 1`. 

@yjose what do you think ? Would you accept this as a PR ? Also, do I need to add a story in my PR to demonstrate the fix ?

**Comment by JefferyHus** [comment] 2019-12-12 19:01
@zakariaelas good explanation mate, you should add references to your PR with a small description. So far reading your last comment makes sense, I will also give it a look and have a clearer idea. Cheers

**Comment by yjose** [comment] 2020-09-04 02:05
fixed on v2

**Closed** 2020-09-04 02:21 UTC
